### ISSUE TITLE
How do I use /mf force power? 

### ISSUE THREAD

**Issue by Extravent3** [dmccoystephenson/Medieval-Factions#1097]
Hello, do bare in mind, I'm no expert on Minecraft commands so I'm sorry if there's a really obvious answer that I'm oblivious too. Anyways, I was wondering how to use /mf force power as every time I try to use it, it says "Player and desired power must be designated inside single quotes" 

I've tried multiple things too get it too work but it wont change. Please answer my question, thank you. Again sorry if there is a really obvious answer to this question. I am also new too this website, this is my first drafting an issue like this so sorry if I'm missing something I have too do.

**Comment by dmccoystephenson** [comment]
The usage of the command is "/mf force power 'player name' 'new power amount'". The player name and the new power amount need to be in between single quote characters.
