### ISSUE TITLE
Fix /mf force power not working on Paper.

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/Medieval-Factions#1173]
This problem was reported by Laughingspade.

**Comment by CallumJohnson** [comment]
![image](https://user-images.githubusercontent.com/74352969/134596388-fe17a788-5261-4f8a-9fd3-3a995197e31f.png)

Using Paper 277 [Download Here](https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/277/downloads/paper-1.17.1-277.jar)

**Comment by dmccoystephenson** [comment]
Thanks for this!
