### ISSUE TITLE
Are builds not protected in claimed land on Paper?

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/Medieval-Factions#1191]

**Comment by CallumJohnson** [comment]
Confirmed to be working on version: Paper-296
![image](https://user-images.githubusercontent.com/74352969/135712687-dcc12a76-dc97-489b-a130-b3199311c72c.png)

Video Proof: https://youtu.be/ZPBIN3UQVP8

**Comment by dmccoystephenson** [comment]
Excellent! Thank you for looking into this.
