### ISSUE TITLE
Enabling PvP within factions

### ISSUE THREAD

**Issue by whytho42** [dmccoystephenson/Medieval-Factions#1222]
Is there a command or config setting that enables PvP within faction members? I cannot find any setting to enable it. Any information on the subject will be greatly appreciated!

**Comment by dmccoystephenson** [comment]
This faction flag will help:
![image](https://user-images.githubusercontent.com/21204351/145666884-5b4c4d07-9525-4f2d-a187-c43bb78e38b2.png)

To allow friendly fire in your faction, type /mf flags set allowFriendlyFire true 👍

**Comment by dmccoystephenson** [comment]
Also, just so you know, my subreddit might be a better medium for questions like this.
https://www.reddit.com/r/dansplugins/

I don't mind questions wherever I get them, but I figured I'd mention this.
