### ISSUE TITLE
map autofill doesnt work in game but works in dynmap

### ISSUE THREAD

**Issue by AqilHafiyYT** [dmccoystephenson/Medieval-Factions#1259]
![Screenshot 2022-01-05 182703](https://user-images.githubusercontent.com/70635535/148202328-165c76ab-ef2c-4284-9a85-ad325a5e90b2.png)
![Screenshot 2022-01-05 182655](https://user-images.githubusercontent.com/70635535/148202341-7b82673d-5a8d-4428-a8c9-981866e49379.png)

**Comment by dmccoystephenson** [comment]
The territory getting filled in on the dynmap is actually a bug. I just realized there's not an issue for it, so I've created it here: #1305
