### ISSUE TITLE
Restructuring of the claim commands

### ISSUE THREAD

**Issue by Kyrenic** [dmccoystephenson/Medieval-Factions#1638]
I noticed that the current claim-related commands are all different and don't take advantage of the autocomplete feature, so I'm proposing a rework on how they are used. It should be a pretty simple rework since only the names are changed. This should also make it easier and more intuitive to use since autocomplete can suggest all of these to the user, so that they can visually see all of the options available to them instead of having to use the wiki.

1. **/mf claim auto** to replace **/mf autoclaim**
2. **/mf claim fill** to replace **/mf fillclaim**
3. **/mf claim check** to replace **/mf checkclaim**
3. **/mf unclaim all** to replace **/mf unclaimall**

**Comment by dmccoystephenson** [comment]
I created #1640 to implement backwards compatibility for the old commands.

**Comment by dmccoystephenson** [comment]
This issue was resolved by the following commit: 8789c96d2733664ae98133e9119b5438013285b4
