### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [dmccoystephenson/Medieval-Factions#395]
Hi, is there certain placeholders that would work with scoreboards?
or no
Like Faction power or name

**Comment by dmccoystephenson** [comment]
Hey NXxEpicXCreeprxX,

I'm not familiar with placeholders. Could you explain a little more about them? I don't believe I've added support for that, but I'm sure I could figure it out if I have more of an idea of what you're talking about.

 - Daniel

**Comment by dmccoystephenson** [comment]
I've turned this into an unplanned epic. I'll assign tasks once I know more about placeholders.
