### ISSUE TITLE
Possible Bug with Smokers (Needs to be reproduced)

### ISSUE THREAD

**Issue by philbgarner** [dmccoystephenson/Medieval-Factions#737]
Rustee reported that smokers use fuel but do not cook food.

**Comment by CallumJohnson** [comment]
[Smoker Bug - Failed to Recreate. (Video Proof)](https://www.youtube.com/watch?v=__bZhfLUbu4)

Tried different types of raw items, and different fuel-types, with no bug present.
I believe its safe to close this issue.

**Comment by dmccoystephenson** [comment]
Sounds good, thanks @CallumJohnson!
