### ISSUE TITLE
Fix /mf lock not working with gates. (issue needs to be verified)

### ISSUE THREAD

**Issue by TodAufDerFlutch** [dmccoystephenson/Medieval-Factions#759]
I found an issue with /mf lock, It states when you type /mf help that you can only lock doors and chests however when you it gives you an error saying this.
![image](https://user-images.githubusercontent.com/19418103/99031797-f4810780-2545-11eb-92d7-65547557c3ad.png)
In this case I was clicking a gate.

**Comment by Mr-Deej** [comment]
This issue can be closed, cannot replicate in v4.5.1+
