### ISSUE TITLE
Make DisbandCommand.java and LeaveCommand.java reference the same method for removing a faction.

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/Medieval-Factions#797]

**Comment by CallumJohnson** [comment]
Technically, the new implementation of the commands does this, as if the Player owns a faction, it redirects the command to the disband command.
[Referenced Code line](https://github.com/dmccoystephenson/Medieval-Factions/blob/46254612662010cde3dc7d12ada76ea2717a4675/src/main/java/dansplugins/factionsystem/commands/LeaveCommand.java#L28)

**Comment by dmccoystephenson** [comment]
Sounds good!
