### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Giorgis20** [dmccoystephenson/Medieval-Factions#893]
![test](https://user-images.githubusercontent.com/55145425/105006072-cedd1680-5a3e-11eb-86a6-c614bd70e0fb.png)
![Στιγμιότυπο οθόνης 2021-01-19 101122](https://user-images.githubusercontent.com/55145425/105006077-cf75ad00-5a3e-11eb-885d-d04f9f45831d.png)
![Στιγμιότυπο οθόνης 2021-01-19 101133](https://user-images.githubusercontent.com/55145425/105006079-d00e4380-5a3e-11eb-9c6f-4e928e2c32bb.png)

I recently noticed these errors showing up in the console. Are they important? If they are is it an issue with the plugin or an issue with the configuration or server version?

**Comment by dmccoystephenson** [comment]
Thanks for reporting this 👍 I don't like to show stack traces in the console, so this is likely not intended. I'll look into it when I can :)

**Comment by dmccoystephenson** [comment]
@Giorgis20 Can you let me know the following when you have the chance?

- the version of minecraft you're running
- the version of the plugin you're using
- whether you're using Paper or Spigot or something else
- what was happening when the error occurred

**Comment by Giorgis20** [comment]
Minecraft Version: 1.16.5
Plugin Version: 3.6.2
I am using paper 1.16.5 build 434
What was happening when the error occured: unfortunately I don't know since when this error showed up I was just checking the console

**Comment by Giorgis20** [comment]
Recently though, this error came up: 
![Στιγμιότυπο οθόνης 2021-02-16 082820](https://user-images.githubusercontent.com/55145425/108026676-7a26be80-7031-11eb-9d18-945af7891089.png)

It occured 3-4 seconds after someone typed /f home (I only saw through console)

**Comment by CallumJohnson** [comment]
Fixed alongside #1155.
This error is now fixed, #1155 showed the same error messages and #1162 fixed them.

@dmccoystephenson could you close this?

**Comment by dmccoystephenson** [comment]
Thanks for the heads up!
