### ISSUE TITLE
Special characters in the translated text for the plugin turn into incomprehensible symbols in-game.

### ISSUE THREAD

**Issue by Horuse** [dmccoystephenson/Medieval-Factions#971]
![image](https://user-images.githubusercontent.com/39675195/112728102-37a8a980-8f2e-11eb-8c73-01512572d1ec.png)
in the language file itself everything is fine
![image](https://user-images.githubusercontent.com/39675195/112728148-6de62900-8f2e-11eb-91c2-b261dacc6bf1.png)

**Comment by dmccoystephenson** [comment]
Yeah this is an unfortunate one. When programming the Localization feature, I tested it on a server hosted on ServerMiner and had no problems. When I deployed the finished version to my community server hosted on PebbleHost, I ran into this problem. I'm not sure what causes it, unfortunately.

Can you let me know what server provider you're using? @Horuse

**Comment by Horuse** [comment]
I managed to find how to solve the problem
![image](https://user-images.githubusercontent.com/39675195/112750256-48116080-8fd0-11eb-8235-8094f869e69c.png)
need to add this line to your start.bat
